apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: securecodebox-operator
  namespace: argocd
  annotations:
    description: "SecureCodeBox operator"
spec:
  project: default
  sources:
    - repoURL: "oci://ghcr.io/securecodebox/helm/operator"
      targetRevision: "5.1.0"
      chart: operator
      helm:
        valueFiles:
          - $values/infrastructure/securecodebox/values.yaml
    - repoURL: "https://github.com/naqa92/portfolio-ultime-config.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: securecodebox-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
