serviceAccount:
  name: securecodebox-operator

minio:
  enabled: false

s3:
  enabled: true
  endpoint: "s3.eu-west-3.amazonaws.com"
  bucket: "portfolio-ultime-securecodebox"
  region: "eu-west-3"
  authType: aws-irsa # évite la création de "scb-autodiscovery-minio"
