apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory # TODO: changer staging en prod
    email: contact@zoneinfra.com
    privateKeySecretRef:
      name: letsencrypt-key
    solvers:
      - dns01:
          route53:
            region: eu-west-3
            hostedZoneID: Z075458018F27SBDB41PA # Zone ID Route 53
