apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zap-automation-framework
  namespace: argocd
  annotations:
    description: "ZAP Automation Framework pour security testing"
spec:
  project: default
  source:
    repoURL: "oci://ghcr.io/securecodebox/helm/zap-automation-framework"
    targetRevision: "5.1.0"
    chart: zap-automation-framework
  destination:
    server: https://kubernetes.default.svc
    namespace: demo # namespace où les scans seront lancés
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      annotations:
        auto-discovery.securecodebox.io/enabled: "true"
