config:
  serviceAutoDiscovery:
    enabled: true
    scanConfigs:
      - scanType: "zap-automation-framework"
        name: "zap"
        repeatInterval: "168h" # 1x/semaine (valeur par défaut)
        parameters:
          - "-autorun"
          - "/home/securecodebox/scb-automation/automation.yaml" # mountPath de la ConfigMap auto-générée (valeur par défaut)
        env:
          - name: TARGET_URL
            value: "http://todolist.demo.svc.cluster.local:5000"
