headlamp:
  pluginsManager:
    enabled: true
    configContent: |
      plugins:
        - name: kubescape
          source: https://artifacthub.io/packages/headlamp/kubescape-headlamp-plugin/headlamp_kubescape
          version: "0.10.3"
      installOptions:
        parallel: true
        maxConcurrent: 2
    baseImage: node:lts-alpine
    version: latest
  config:
    watchPlugins: true # active la surveillance pour recharger automatiquement les plugins
    pluginsDir: "/build/plugins"
