headlamp:
  pluginsManager:
    enabled: false

  initContainers:
    - name: fetch-kubescape-plugin
      image: quay.io/kubescape/headlamp-plugin:0.10.3
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "Copying plugin files..."
          mkdir -p /shared-plugins/kubescape
          cp -r /plugin/* /shared-plugins/kubescape/
          echo "Files copied:"
          ls -la /shared-plugins/kubescape/
      volumeMounts:
        - name: shared-plugins
          mountPath: /shared-plugins

  extraVolumes:
    - name: shared-plugins
      emptyDir: {}

  extraVolumeMounts:
    - name: shared-plugins
      mountPath: /headlamp/plugins

  config:
    watchPlugins: true
    pluginsDir: "/headlamp/plugins"
