apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: db
spec:
  instances: 2
  storage:
    size: 5G
    storageClass: gp2 # Storage Class du provisioner aws-ebs
  bootstrap:
    initdb:
      database: todolist
      owner: zoneinfra
