apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-cluster
  namespace: argocd
  annotations:
    description: "Cluster CNPG PostgreSQL pour l'application todolist"
spec:
  project: default
  source:
    path: applications/cnpg/manifests/
    repoURL: "https://github.com/naqa92/portfolio-ultime-config.git"
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: "demo"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
