apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-registry-es
  namespace: demo
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: ghcr-registry-secret
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        ".dockerconfigjson": |
          {{- $username := "naqa92" -}}
          {{- $email := "contact@zoneinfra.com" -}}
          {{- $token := .token -}}
          {{- $auth := printf "%s:%s" $username $token | b64enc -}}
          {{- $cfg := dict "auths" (dict "ghcr.io" (dict "username" $username "password" $token "email" $email "auth" $auth)) -}}
          {{- $cfg | toJson | b64enc -}}
  data:
    - secretKey: token
      remoteRef:
        key: ghcr-token
