apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-registry-es
  namespace: demo
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: ghcr-registry-secret
    template:
      engineVersion: v2
      type: kubernetes.io/dockerconfigjson
      data:
        ".dockerconfigjson": |
          {{- $auth := printf "%s:%s" "naqa92" .token | b64enc -}}
          {{- $cfg := dict "auths" (dict "ghcr.io" (dict "username" "naqa92" "password" .token "email" "contact@zoneinfra.com" "auth" $auth)) -}}
          {{- $cfg | toJson | b64enc -}}
  data:
    - secretKey: token
      remoteRef:
        key: ghcr-token
