apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
  annotations:
    description: "Interface web pour Kubernetes"
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  sources:
    - repoURL: "https://kubernetes-sigs.github.io/headlamp/"
      targetRevision: "0.36.0"
      chart: headlamp
      helm:
        valueFiles:
          - $values/infrastructure/headlamp/values.yaml
    - repoURL: "https://github.com/naqa92/portfolio-ultime-config.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
