# ArgoCD Application for AWS Load Balancer Controller
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://aws.github.io/eks-charts
    chart: aws-load-balancer-controller
    targetRevision: 1.13.4
    helm:
      valueFiles:
        - ../../values/cert-manager-sync-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-alb
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
