apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    description: "CRDs pour certificats TLS automatique avec Let's Encrypt"
spec:
  project: default
  sources:
    - repoURL: "https://charts.jetstack.io"
      targetRevision: "1.18.2"
      chart: cert-manager
      helm:
        valueFiles:
          - $values/values/cert-manager-values.yaml
    - repoURL: "https://github.com/naqa92/portfolio-ultime-config.git"
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-certmanager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
