apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-sync
  namespace: argocd
  annotations:
    description: "Synchronisation automatique des certificats cert-manager avec ACM"
spec:
  project: default
  sources:
    - repoURL: "https://github.com/naqa92/portfolio-ultime-config.git"
      targetRevision: HEAD
      path: apps/cert-manager-sync/
      helm:
        valueFiles:
          - $values/values/cert-manager-sync-values.yaml
    - repoURL: "https://github.com/naqa92/portfolio-ultime-config.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-certmanager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
