apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    description: "ClusterIssuer pour génération automatique des certificats TLS"
spec:
  project: default
  source:
    path: apps/cert-manager/
    repoURL: https://gitlab.com/naqa92/argocd-infra.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: "" # cluster-wide
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
