apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    description: "Gestion des enregistrements DNS Route 53"
spec:
  project: default
  source:
    repoURL: "https://kubernetes-sigs.github.io/external-dns/"
    targetRevision: "1.19.0"
    chart: external-dns
    helm:
      valueFiles:
        - ../../values/external-dns-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
