apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    description: "Synchronisation automatique des secrets externes"
spec:
  project: default
  sources:
    - repoURL: "https://charts.external-secrets.io"
      targetRevision: "0.20.1"
      chart: external-secrets
      helm:
        valueFiles:
          - $values/values/external-secrets-values.yaml
    - repoURL: "https://github.com/naqa92/portfolio-ultime-config.git"
      targetRevision: main
      ref: values
      path: apps/external-secrets/ # ArgoCD va compiler les deux sources et reconciler l’ensemble. (values + CRDs)
  destination:
    server: "https://kubernetes.default.svc"
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Permet de gérer les annotations trop longues dans les CRDs
