apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: scb-autodiscovery
  namespace: argocd
  annotations:
    description: "ConfigMap pour zap-automation-framework"
spec:
  project: default
  source:
    path: apps/autodiscovery/
    repoURL: "https://github.com/naqa92/portfolio-ultime-config.git"
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: "demo"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
