apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todolist
  namespace: argocd
  annotations:
    description: "Application python Flask de gestion de tâches"
spec:
  project: default
  sources:
    - repoURL: "oci://ghcr.io/naqa92/charts/todolist"
      targetRevision: "0.1.9"
      chart: todolist
      helm:
        valueFiles:
          - $values/values/todolist-values.yaml
    - repoURL: "https://github.com/naqa92/portfolio-ultime-config.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: demo # créé par zap-automation-framework
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
