apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zap-automation-framework
  namespace: argocd
  annotations:
    description: "ZAP automation framework pour les tests de sécurité web"
spec:
  project: default
  source:
    repoURL: "oci://ghcr.io/securecodebox/helm/zap-automation-framework"
    targetRevision: 5.0.0
    chart: zap-automation-framework
  destination:
    server: https://kubernetes.default.svc
    namespace: securecodebox-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
