apiVersion: v1
kind: ConfigMap
metadata:
  name: zap-automation-framework-passive-config
data:
  automation.yaml: |-
    env:
      contexts:
        - name: passive-config
          urls: ["${TARGET_URL}"] # dynamique grâce à l'env var
    jobs:
      - type: spider # DAST Passif
        parameters:
          context: passive-config
          maxDuration: 2 # attendre max 2 min que le spider ait fini
      - type: passiveScan-wait # Scan sans spider et activeScan pour éviter toute injection
        parameters:
          maxDuration: 5 # attendre max 5 min que les alertes passives soient générées
      - type: report
        parameters:
          template: traditional-xml # traditional-html, traditional-pdf, modern (html), json, sarif-json, md, wiki (garder xml pour le parser)
          reportDir: /home/securecodebox/
          reportFile: zap-results.xml
