apiVersion: db.atlasgo.io/v1alpha1
kind: AtlasSchema
metadata:
  name: todos
spec:
  credentials:
    scheme: postgres
    port: 5432
    host: db-rw.demo
    user: zoneinfra
    passwordFrom:
      secretKeyRef:
        key: password
        name: db-app
    database: todolist
  schema:
    sql: |
      create table todos (
        id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        title varchar(100) not null,
        complete boolean not null default false
      );
