apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    description: "Configurations pour la synchronisation automatique des secrets externes"
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    path: infrastructure/external-secrets/manifests/
    repoURL: "https://github.com/naqa92/portfolio-ultime-config.git"
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: "" # Namespace défini dans chaque manifest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
