apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    description: "ClusterIssuer pour génération automatique des certificats TLS"
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    path: infrastructure/cert-manager/manifests/
    repoURL: "https://github.com/naqa92/portfolio-ultime-config.git"
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: certmanager-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
