apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-crds
  namespace: argocd
  annotations:
    description: "CRDs pour certificats TLS automatique avec Let's Encrypt"
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  sources:
    - repoURL: "https://charts.jetstack.io"
      targetRevision: "v1.19.1"
      chart: cert-manager
      helm:
        valueFiles:
          - $values/infrastructure/cert-manager/values.yaml
    - repoURL: "https://github.com/naqa92/portfolio-ultime-config.git"
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: certmanager-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
