apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-helm-repo-es
  namespace: argocd
spec:
  refreshInterval: "5m"
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: ghcr-helm-repo-secret
    template:
      engineVersion: v2
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: "helm"
        name: "ghcr"
        url: "oci://ghcr.io/naqa92/charts"
        username: "naqa92"
        password: "{{ .token }}"
        enableOCI: "true"
  data:
    - secretKey: token
      remoteRef:
        key: ghcr-token
