apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todolist
  namespace: argocd
  annotations:
    description: "Application Todolist"
spec:
  project: default
  sources:
    - repoURL: "oci://ghcr.io/naqa92/charts/todolist"
      targetRevision: "*" # version définie dans les values
      chart: todolist
      helm:
        valueFiles:
          - $values/applications/todolist/values.yaml
    - repoURL: "https://github.com/naqa92/portfolio-ultime-config.git"
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
